import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {GoogleOAuthProvider} from "@react-oauth/google"
import { Toaster } from 'react-hot-toast';
import './globals.css'
import TanstackProvider from '@/providers/TanstackProvider';
import SideBar from '@/components/SideBar';
import GoogleLoginBtn from '@/components/GoogleLoginBtn';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
        <GoogleOAuthProvider clientId='523471836531-dndr7ppg4ndqtt4bmlmqd8roaap015uc.apps.googleusercontent.com'>
        <div className='grid grid-cols-12 h-screen w-screen'>
        <SideBar/>
        {children}
        <GoogleLoginBtn/>
      </div>
          <Toaster/>
        </GoogleOAuthProvider>
        </TanstackProvider>
        </body>
    </html>
  )
}
